---

# to gather facts on what ansible calls the ansible_distribution run:
# ansible 10.0.0.43 -m gather_facts | grep ansible_distribution


- hosts: home
  gather_facts: yes
  become: true
  
  tasks:

  - name: Update cache and perform dist-upgrade
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'
  
  - name: Check if a reboot is required
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Reboot the server (if required)
    ansible.builtin.reboot:
    when: reboot_required_file.stat.exists == true

  - name: Remove dependencies no longer required
    ansible.builtin.apt:
      autoremove: yes