---

# to gather facts on what ansible calls the ansible_distribution run:
# ansible 10.0.0.43 -m gather_facts | grep ansible_distribution


- hosts: all
  become: true
  tasks:

  - name: Update OS and NO RESTART
    apt: 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update OS and NO RESTART
    dnf: 
      update_cache:  yes
    when: ansible_distribution == "Rocky"
