---

# to gather facts on what ansible calls the ansible_distribution run:
# ansible 10.0.0.43 -m gather_facts | grep ansible_distribution


- hosts: lab
  become: true
  
  tasks:

  - name: Update Rocky and NO RESTART
    dnf: 
      update_cache:  yes
    when: ansible_distribution == 'Rocky'

  - name: Update Rocky and NO RESTART
    dnf:
      name: "*"
      state: latest
    when: ansible_distribution == 'Rocky'