---

# to gather facts on what ansible calls the ansible_distribution run:
# ansible 10.0.0.43 -m gather_facts | grep ansible_distribution


- hosts: all
  become: true
  
  tasks:

  - name: Update Ubuntu Systems and NO RESTART
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'