---

# to gather facts on what ansible calls the ansible_distribution run:
# ansible 10.0.0.43 -m gather_facts | grep ansible_distribution


- hosts: all
  become: true
  
  tasks:

  - name: Update cache and perform dist-upgrade
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'
  
  - name: Check if a reboot is required
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Reboot the server (if required)
    ansible.builtin.reboot:
    when: reboot_required_file.stat.exists == true

  - name: Remove dependencies no longer required
    ansible.builtin.apt:
      autoremove: yes

  ## Seperating Operatin Systems 
  
  - name: Update Rocky Linux
    dnf: 
      update_cache:  yes
    when: ansible_distribution == 'Rocky'

  - name: Update Rocky and NO RESTART
    dnf:
      name: "*"
      state: latest
    when: ansible_distribution == 'Rocky'

  - name: install yum-utils if needed
    ansible.builtin.dnf:
      name: yum-utils
      state: present

  - name: check if reboot is required
    ansible.builtin.shell:
      cmd: "needs-restarting -r -s"
    register: needs_restarting
    changed_when: needs_restarting.rc == 1
    failed_when: false
    notify: do reboot if needed
  
  handlers:
    - name: do reboot if needed
      ansible.builtin.reboot: